# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      - restore_cache:
          keys: 
            - deps-{{ .Branch}}-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: |
            sudo apt-get install -y libopencv-dev
            python3 -m venv venv
            . venv/bin/activate
            pip install mypy
            pip install tox
            pip install -r requirements.txt

      - save_cache:
          key: deps-{{ .Branch}}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: Type check
          command: |
            . venv/bin/activate
            make typecheck

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make test
